apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: foundation
  source:
    repoURL: git@github.com:chow612/traffic-violation-detection.git
    targetRevision: main
    path: devops/infrastructure/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ServerSideApply=true