apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis-master
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command:
            - sh
            - -c
            - exec redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes
          ports:
            - name: redis
              containerPort: 6379
          envFrom:
            - secretRef:
                name: redis-secret
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
        storageClassName: local-path
