apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: foundation
  namespace: argocd
spec:
  description: Traffic Violation Detection - foundation workloads
  sourceRepos:
    - 'git@github.com:chow612/traffic-violation-detection.git'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
